/**
 * AUTO-GENERATED — do not edit manually.
 * Source: Notion "Database IT" (3097355e7f7f819caf33d0fd0739cc5b)
 * Generated: 2026-03-24T10:33:01.798Z
 * Run: NOTION_API_KEY=ntn_xxx npx tsx scripts/fetch-rinnovo-data.ts
 */

export interface RinnovoPermit {
  /** Full name from Notion DB */
  notionName: string;
  /** Short key used in tree node IDs (r_end_<treeKey>) */
  treeKey: string;
  /** Notion category: Studio/Lavoro, Protezione, Cure Mediche, Motivi Familiari */
  category: string;
  /** How long the permit lasts */
  duration: string;
  /** True if renewal is explicitly marked as not applicable */
  rinnovoNonApplicabile: boolean;
  /** Renewal method: 'KIT', 'personalmente', 'n/a', 'rinnovabile previa conversione' */
  modRinnovo: string[];
  /** Documents required for renewal */
  docRinnovo: string[];
  /** Extra notes/warnings about renewal */
  infoExtra: string;
  /** Whether conversion is possible (free text from Notion) */
  possoConvertire: string;
}

export const rinnovoPermits: RinnovoPermit[] = [
  {
    notionName: 'Affidamento a familiari entro il quarto grado',
    treeKey: 'affidamento',
    category: 'Motivi Familiari',
    duration: 'fino al compimento di 18 anni',
    rinnovoNonApplicabile: true,
    modRinnovo: ['n/a'],
    docRinnovo: [
    ],
    infoExtra: '',
    possoConvertire: 'Si, permesso per studio; per lavoro; per attesa occupazione',
  },
  {
    notionName: 'Apolidia',
    treeKey: 'apolidia',
    category: 'Protezione',
    duration: '5 anni',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 80.46 €',
      'Permesso in scadenza',
      'Decisione che dà lo status di apolide',
    ],
    infoExtra: '',
    possoConvertire: '',
  },
  {
    notionName: 'Lavoro artistico',
    treeKey: 'artistico',
    category: 'Studio/Lavoro',
    duration: '',
    rinnovoNonApplicabile: false,
    modRinnovo: [],
    docRinnovo: [
    ],
    infoExtra: '',
    possoConvertire: '',
  },
  {
    notionName: 'Asilo (status rifugiato)',
    treeKey: 'asilo',
    category: 'Protezione',
    duration: '5 anni',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 30.46 €',
      'Dichiarazione di ospitalità o contratto di affitto o certificato di residenza',
      'Permesso in scadenza',
      'Decisione della Commissione o del Tribunale',
    ],
    infoExtra: '',
    possoConvertire: '',
  },
  {
    notionName: 'Assistenza minore ("Articolo 31")',
    treeKey: 'ass_minori',
    category: 'Motivi Familiari',
    duration: '2 anni',
    rinnovoNonApplicabile: false,
    modRinnovo: ['personalmente'],
    docRinnovo: [
      'n/a',
    ],
    infoExtra: 'Attenzione: se il permesso che chiedi è di solo un anno, il bollettino è 70,46\n\nAttenzione: alcune Questure potrebbero chiedere un documento di identità dei figli, ma questo non dovrebbe essere necessario\n\nAttenzione: questo permesso non può essere rinnovato: bisogna fare una nuova causa al Tribunale per i minorenni e chiedere un nuovo permesso di soggiorno',
    possoConvertire: 'prima della sua scadenza in permesso per motivi di lavoro. o dopo 5 anni pds ue per soggiornanti lungo periodo',
  },
  {
    notionName: 'Attesa occupazione',
    treeKey: 'att_occ',
    category: 'Studio/Lavoro',
    duration: '1 anno',
    rinnovoNonApplicabile: false,
    modRinnovo: ['n/a'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 70.46 o 80.46 (dipende dalla durata del permesso)',
      'Copia del passaporto (non scaduto)',
      'Iscrizione al centro per l\'impiego',
    ],
    infoExtra: 'Nota: se hai un permesso per studio e stai chiedendo questo permesso, devi anche portare il certificato di conclusione del percorso di studi \nNota: se hai un altro tipo di permesso, ad esempio per motivi di famiglia, puoi provare a chiedere questo permesso per attesa occupazione ma devi portare una prova che hai lavorato recentemente (ad es. ultime buste paga)\n\nNOTA aggiuntiva sul rinnovo: difficile ottenerlo, in casi eccezionali si può ma serve provare particolare vulnerabilità (relazione dei Servizi)',
    possoConvertire: '',
  },
  {
    notionName: 'Calamità naturale',
    treeKey: 'calamita',
    category: 'Protezione',
    duration: '6 mesi',
    rinnovoNonApplicabile: false,
    modRinnovo: ['personalmente'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Dichiarazione di ospitalità o contratto di affitto o certificato di residenza',
      'Permesso in scadenza',
      'Prova della calamità naturale',
    ],
    infoExtra: 'Attenzione: per questo tipo di permesso, se non hai dichiarazione di ospitalità, dovrebbe bastare l’indicazione di un domicilio. La Questura ha bisogno di un indirizzo per sapere dove sei\n\nAttenzione: alcune Questura potrebbero dare questo permesso in formato elettronico e quindi chiedere il pagamento di un bollettino postale da 30,46\n\nAttenzione: alcune Questure potrebbero chiedere il passaporto',
    possoConvertire: '',
  },
  {
    notionName: 'Carta di soggiorno per familiari di italiani "dinamici"',
    treeKey: 'carta_fam_ita',
    category: 'Motivi Familiari',
    duration: '10anni',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 80.46 €',
      'Copia del passaporto (non scaduto)',
      'Dichiarazione di ospitalità o contratto di affitto o certificato di residenza',
      'Permesso in scadenza',
      'Documento che prova il legame di famiglia (ad esempio "stato di famiglia")',
      'Prova dei mezzi economici sufficienti',
    ],
    infoExtra: 'nota rinnovo: dopo cinque anni la carta di soggiorno diventa permanente - assicurati che la durata della tua nuova carta sia almeno 10 anni',
    possoConvertire: '',
  },
  {
    notionName: 'Carta di soggiorno per familiari di cittadini UE',
    treeKey: 'carta_fam_ue',
    category: 'Motivi Familiari',
    duration: '10anni',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 30.46 €',
      'Copia del passaporto (non scaduto)',
      'Dichiarazione di ospitalità o contratto di affitto o certificato di residenza',
      'Permesso in scadenza',
      'Documento che prova il legame di famiglia (ad esempio "stato di famiglia")',
      'Prova dei mezzi economici sufficienti',
    ],
    infoExtra: 'nota rinnovo: dopo cinque anni la carta di soggiorno diventa permanente - assicurati che la durata della tua nuova carta sia almeno 10 anni',
    possoConvertire: '',
  },
  {
    notionName: 'UE per soggiornanti di lungo periodo ("Carta di soggiorno")',
    treeKey: 'carta_ue',
    category: 'Studio/Lavoro',
    duration: 'illimitata',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 30.46 €',
      'Dichiarazione di ospitalità o contratto di affitto o certificato di residenza',
    ],
    infoExtra: 'Alcune Questure chiedono idoneità alloggiativa anche se chiedi solo per te; la legge non lo chiede e probabilmente un tribunale ti darà ragione\n\nAlcune questure chiedono prova di assenza di condanne (certificato di casellario giudiziale e carichi pendenti)\n\nNOTA rinnovo: si chiama aggiornamento (bisogna solo provare foto e aggiornamento della residenza). Molte Questure potrebbero chiedere altri documenti come se fosse un rinnovo. Quindi se li hai tutti, mettili nel kit! Se non li hai, chiedi lo stesso l’aggiornamento e se la Questura rigetta la tua domanda, rivolgiti a un aiuto legale.\n\nNOTA documenti primo rilascio\nQuali documenti devo mettere nel Kit se chiedo il permesso anche per mia moglie/marito o per un genitore?\n• Moduli 1 e 2: il modulo 2 si compila solo se il familiare ha un reddito proprio\n• Fotocopia del tuo passaporto e permesso di soggiorno\n• Fotocopia del passaporto e permesso di soggiorno di tua moglie/marito o del genitore\n• Certificato del casellario e dei carichi pendenti da chiedere alla Procura\n• Certificato di residenza e stato di famiglia\n• Documenti sulla casa (atto di proprietà, contratto di affitto o dichiarazione di ospitalità)\n• Certificato di idoneità dell\'alloggio dato dal Comune\n• Documenti sul reddito (dichiarazione dei redditi, CUD, buste paga, contratto di lavoro, anche del tuo familiare se contribuisce al reddito della famiglia)\n• Attestato di italiano livello A2\n\nQuali documenti devo mettere nel Kit se chiedo il permesso anche per i miei figli minori?\n• Modulo 1\n• Fotocopia del tuo passaporto e permesso di soggiorno\n• Fotocopia del passaporto e permesso di soggiorno di tuo figlio\n• Certificato di residenza e stato di famiglia\n• Documenti sul reddito (dichiarazione dei redditi, CUD, buste paga, contratto di lavoro)\n• Certificato di idoneità dell\'alloggio\n• Certificato di frequenza scolastica se il minore deve andare a scuola per legge\n• Attestato di italiano livello A2 (se il minore non ha già un diploma di scuola media o superiore)\nRicorda che ogni familiare sopra i 14 anni deve compilare un Kit proprio. Se tuo figlio ha meno di 14 anni, puoi metterlo nel tuo Kit.',
    possoConvertire: '',
  },
  {
    notionName: 'Cure mediche per persona gravemente malata che si trova già in Italia',
    treeKey: 'cure_grave',
    category: 'Cure Mediche',
    duration: '1 anno',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Dichiarazione di ospitalità o contratto di affitto o certificato di residenza',
      'Permesso in scadenza',
      'Documenti che provano che la tua malattia non si può curare bene nel tuo paese',
      'Documenti medici (ospedale pubblico o medico pubblico) che provano la tua malattia',
    ],
    infoExtra: 'Attenzione: per questo tipo di permesso, se non hai dichiarazione di ospitalità, dovrebbe bastare l’indicazione di un domicilio. La Questura ha bisogno di un indirizzo per sapere dove sei\n\nAttenzione: alcune Questure potrebbero chiedere il passaporto anche se non è necessario per questo tipo di permesso\n\nAttenzione: alcune Questura potrebbero dare questo permesso in formato elettronico e quindi chiedere il pagamento di un bollettino postale da 30,46',
    possoConvertire: 'Si: permesso per lavoro; motivi familiari',
  },
  {
    notionName: 'Cure mediche - donna in stato di gravidanza o con figlio minore di 6 mesi',
    treeKey: 'cure_gravidanza',
    category: 'Cure Mediche',
    duration: '1 anno',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'n/a',
    ],
    infoExtra: 'Attenzione: per questo tipo di permesso, se non hai dichiarazione di ospitalità, dovrebbe bastare l’indicazione di un domicilio. La Questura ha bisogno di un indirizzo per sapere dove sei\n\nAttenzione: alcune Questura potrebbero dare questo permesso in formato elettronico e quindi chiedere il pagamento di un bollettino postale da 30,46',
    possoConvertire: '',
  },
  {
    notionName: 'Cure mediche - padre di bambino minore di 6 mesi o che sta per nascere in Italia',
    treeKey: 'cure_padre',
    category: 'Cure Mediche',
    duration: '1 anno',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'n/a',
    ],
    infoExtra: 'Se sei sposato e convivente con la madre del bambino, puoi avere questo permesso senza problemi.\n\nSe NON sei sposato e/o NON convivi, potrebbe essere un problema avere questo permesso e quindi chiedi un consiglio legale qualificato',
    possoConvertire: '',
  },
  {
    notionName: 'Cure mediche dopo ingresso con visto per cure mediche',
    treeKey: 'cure_visto',
    category: 'Cure Mediche',
    duration: '1 anno',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 30.46 €',
      'Copia del passaporto (non scaduto)',
      'Dichiarazione di ospitalità o contratto di affitto o certificato di residenza',
      'Permesso in scadenza',
      'Dichiarazione dell\'ospedale per necessità di continuare le cure in Italia',
      'Indicazione mezzi sostentamento (vitto e alloggio)',
      'Polizza assicurativa copertura sanitaria o iscrizione volontaria a SSN',
    ],
    infoExtra: '',
    possoConvertire: '',
  },
  {
    notionName: 'Famiglia - senza nullaosta per ricongiungimento ("coesione familiare")',
    treeKey: 'fam_coesione',
    category: 'Motivi Familiari',
    duration: 'Segue pds parente',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 80.46 €',
      'Copia del passaporto (non scaduto)',
      'Permesso in scadenza',
      'Prova del reddito minimo (CUD o buste paga o dichiarazione dei redditi o altro)',
      'Certificato di idoneità alloggiativa',
      'Copia del permesso di soggiorno del famigliare con cui fare la coesione',
      'Documento che prova il legame di famiglia (ad esempio "stato di famiglia")',
    ],
    infoExtra: '',
    possoConvertire: 'Si: lavoro; studio; attesa occupazione',
  },
  {
    notionName: 'Famiglia - convivente con parente cittadino italiano entro il secondo grado',
    treeKey: 'fam_convivente_ita',
    category: 'Motivi Familiari',
    duration: '2 anni',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 80.46 €',
      'Copia del passaporto (non scaduto)',
      'Prova della convivenza (basta la dichiarazione di ospitalità)',
      'Permesso in scadenza',
      'Documento che prova il rapporto di parentela con il cittadino italiano',
    ],
    infoExtra: 'Attenzione: per questo tipo di permesso, se non hai dichiarazione di ospitalità, dovrebbe bastare l’indicazione di un domicilio. La Questura ha bisogno di un indirizzo per sapere dove sei\n\nAttenzione: se non hai il passaporto, chiedi comunque questo permesso; il passaporto per legge non dovrebbe essere richiesto\n\nAttenzione: normalmente la polizia farà delle verifiche per vedere se vivi veramente con il cittadino italiano',
    possoConvertire: 'Si, studio o lavoro',
  },
  {
    notionName: 'Famiglia - genitore di cittadino italiano',
    treeKey: 'fam_genitore_ita',
    category: 'Motivi Familiari',
    duration: '2 anni',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 80.46 €',
      'Copia del passaporto (non scaduto)',
      'Permesso in scadenza',
      'certificato di residenza del minore in Italia',
      'Documento di identità del cittadino italiano',
    ],
    infoExtra: 'Attenzione: alcune Questure potrebbero chiedere un certificato che non sei “decaduto” dalla responsabilità come genitore. E’ un modello che si chiede al Tribunale per i Minorenni\n\nAttenzione: se stai chiedendo questo permesso come conversione da altro permesso, la domanda si fa con kit',
    possoConvertire: 'Si: studio o lavoro',
  },
  {
    notionName: 'Famiglia - dopo ingresso con visto per ricongiungimento familiare',
    treeKey: 'fam_ricong',
    category: 'Motivi Familiari',
    duration: '2 anni',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 80.46 €',
      'Copia del passaporto (non scaduto)',
      'Permesso in scadenza',
      'Prova del reddito minimo (CUD o buste paga o dichiarazione dei redditi o altro)',
      'Copia del permesso di soggiorno del familiare che ha chiesto il ricongiungimento',
      'Documento che prova il legame di famiglia (ad esempio "stato di famiglia")',
    ],
    infoExtra: 'Attenzione: se stai chiedendo questo permesso e hai più di 65 anni devi anche mettere copia dell’assicurazione sanitaria\n\nAttenzione: se hai cambiato casa, alcune Questure per il rinnovo potrebbero chiedereun certificato di idoneità alloggiativa per il rinnovo di questo permesso.',
    possoConvertire: 'Si: lavoro, studio attesa occupazione',
  },
  {
    notionName: 'Famigliari di persone con status di rifugiato o protezione sussidiaria',
    treeKey: 'fam_rifugiato',
    category: 'Protezione',
    duration: '5 anni',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Documento che dimostri il legame di parentela',
      'Permesso di soggiorno del familiare straniero',
    ],
    infoExtra: '',
    possoConvertire: 'Si',
  },
  {
    notionName: 'FAMIT per familiari di cittadini italiani "statici"',
    treeKey: 'famit_statici',
    category: 'Motivi Familiari',
    duration: '5 anni',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 80.46 €',
      'Copia del passaporto (non scaduto)',
      'Dichiarazione di ospitalità o contratto di affitto o certificato di residenza',
      'Permesso in scadenza',
      'Documento che prova il rapporto di parentela con il cittadino italiano (incluso nuovo certificato di matrimonio se è coniuge)',
      'Documento di identità del cittadino italiano',
    ],
    infoExtra: '',
    possoConvertire: 'Si: lavoro; studio',
  },
  {
    notionName: 'Figlio minore di più di 14 anni che vive con i genitori',
    treeKey: 'figlio_14',
    category: 'Motivi Familiari',
    duration: '',
    rinnovoNonApplicabile: false,
    modRinnovo: [],
    docRinnovo: [
    ],
    infoExtra: '',
    possoConvertire: '',
  },
  {
    notionName: 'Lavoro autonomo (conversione da altro permesso)',
    treeKey: 'lav_aut_conv',
    category: 'Studio/Lavoro',
    duration: '2 anni',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 80.46 €',
      'Copia del passaporto (non scaduto)',
      'Dichiarazione di ospitalità o contratto di affitto o certificato di residenza',
      'Permesso in scadenza',
      'Ultima dichiarazione dei redditi',
      'Certificato attribuzione partita IVA o iscrizione al registro delle imprese',
    ],
    infoExtra: 'NOTA: alcune questura potrebbero chiedere l’idoneità alloggiativa',
    possoConvertire: '',
  },
  {
    notionName: 'Lavoro autonomo (dopo ingresso con visto per "flussi")',
    treeKey: 'lav_aut_flussi',
    category: 'Studio/Lavoro',
    duration: '2 anni',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 80.46 €',
      'Copia del passaporto (non scaduto)',
      'Dichiarazione di ospitalità o contratto di affitto o certificato di residenza',
      'Permesso in scadenza',
      'Ultima dichiarazione dei redditi',
      'Certificato attribuzione partita IVA o iscrizione al registro delle imprese',
    ],
    infoExtra: 'Nota: per alcune attività potrebbe essere richiesta l’iscrizione al registro delle imprese.',
    possoConvertire: '',
  },
  {
    notionName: 'Lavoro subordinato (conversione da altro permesso)',
    treeKey: 'lav_sub_conv',
    category: 'Studio/Lavoro',
    duration: '2 anni',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 80.46 €',
      'Copia del passaporto (non scaduto)',
      'Dichiarazione di ospitalità o contratto di affitto o certificato di residenza',
      'Permesso in scadenza',
      'Contratto di lavoro',
      'Prova dei redditi (CUD e/o buste paga)',
      'Certificato UNILAV',
    ],
    infoExtra: 'NOTA: Se il permesso che hai ora è un permesso per minore età, occorre il parere favorevole della Direzione ministeriale art. 32, alla conversione \nNOTA: Se il permesso che hai ora è un permesso per studio, serve il nullaosta alla conversione da chiedere in Prefettura',
    possoConvertire: '',
  },
  {
    notionName: 'Lavoro subordinato (dopo ingresso con visto per "flussi")',
    treeKey: 'lav_sub_flussi',
    category: 'Studio/Lavoro',
    duration: '2 anni',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 80.46 €',
      'Copia del passaporto (non scaduto)',
      'Dichiarazione di ospitalità o contratto di affitto o certificato di residenza',
      'Permesso in scadenza',
      'Contratto di lavoro',
      'Prova dei redditi (CUD e/o buste paga)',
      'Certificato UNILAV',
    ],
    infoExtra: '',
    possoConvertire: '',
  },
  {
    notionName: 'Minore età (per MSNA)',
    treeKey: 'minore',
    category: 'Protezione',
    duration: 'fino al compimento di 18 anni',
    rinnovoNonApplicabile: false,
    modRinnovo: ['n/a'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'permesso precedente',
    ],
    infoExtra: 'Attenzione: alcune Questure potrebbero chiedere un tuo documento di identità con foto (ad esempio passaporto o carta di identità del tuo Paese o certificato di nascita). Se sei già stato registrato in Italia come minore straniero non accompagnato, questi documenti non sono necessari\n\nAttenzione: alcune questure potrebbero chiedere prova del domicilio (dichiarazione di ospitalità o certificato di residenza)\n\nAttenzione: alcune Questura potrebbero dare questo permesso in formato elettronico e quindi chiedere il pagamento di un bollettino postale da 30,46\n\nAttenzione: se hai già un tutore, porta anche la decisione di nomina del tutore.\n\nTi consigliamo comunque di chiedere un aiuto legale qualificato',
    possoConvertire: 'Si: lavoro, studio, attesa occupazione, famiglia, prosieguo amministrativo',
  },
  {
    notionName: 'Integrazione ("Prosieguo amministrativo")',
    treeKey: 'prosieguo',
    category: 'Protezione',
    duration: '',
    rinnovoNonApplicabile: false,
    modRinnovo: ['n/a'],
    docRinnovo: [
      'n/a',
    ],
    infoExtra: 'Attenzione: alcune Questure potrebbero chiedere il passaporto o attestazione di identità consolare',
    possoConvertire: '',
  },
  {
    notionName: 'Protezione sociale vittime di tratta',
    treeKey: 'prot_soc_tratta',
    category: 'Protezione',
    duration: '1 anno',
    rinnovoNonApplicabile: false,
    modRinnovo: ['personalmente'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 30.46 €',
      'Dichiarazione di ospitalità o contratto di affitto o certificato di residenza',
      'Permesso in scadenza',
      'Certificato di residenza',
      'Proposta/parere dell\'Autorità giudiziaria',
      'Relazione dei servizi sociali (se richiesta)',
    ],
    infoExtra: 'ATTENZIONE: ALCUNE QUESTURE POTREBBERO RICHIEDERE IL PASSAPORTO\nNOTA: SCHEDA IN VIA DI VERIFICA\n',
    possoConvertire: '',
  },
  {
    notionName: 'Protezione sociale vittime di violenza domestica',
    treeKey: 'prot_soc_violenza',
    category: 'Protezione',
    duration: '1 anno',
    rinnovoNonApplicabile: false,
    modRinnovo: ['personalmente'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 30.46 €',
      'Dichiarazione di ospitalità o contratto di affitto o certificato di residenza',
      'Permesso in scadenza',
      'Proposta/parere dell\'Autorità giudiziaria',
      'Relazione dei servizi sociali (se richiesta)',
    ],
    infoExtra: 'ATTENZIONE: ALCUNE QUESTURE POTREBBERO RICHIEDERE IL PASSAPORTO\nNOTA: SCHEDA IN VIA DI VERIFICA\n',
    possoConvertire: '',
  },
  {
    notionName: 'Protezione speciale dopo decisione positiva della Commissione o del Tribunale',
    treeKey: 'prot_spec',
    category: 'Protezione',
    duration: 'max 2 anni',
    rinnovoNonApplicabile: false,
    modRinnovo: ['personalmente'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 30.46 €',
      'Permesso in scadenza',
      'Decisione della Commissione o del Tribunale',
    ],
    infoExtra: 'Attenzione: il rinnovo della protezione speciale è una questione complicata, non è sempre certo che si possa avere e ti consigliamo di chiedere subito un aiuto legale',
    possoConvertire: '',
  },
  {
    notionName: 'Protezione sussidiaria',
    treeKey: 'prot_suss',
    category: 'Protezione',
    duration: '5 anni',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 30.46 €',
      'Dichiarazione di ospitalità o contratto di affitto o certificato di residenza',
      'Permesso in scadenza',
      'Decisione della Commissione o del Tribunale',
    ],
    infoExtra: '',
    possoConvertire: '',
  },
  {
    notionName: 'Motivi religiosi',
    treeKey: 'religiosi',
    category: 'Studio/Lavoro',
    duration: '',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 80.46 €',
      'Copia del passaporto (non scaduto)',
      'Dichiarazione di ospitalità o contratto di affitto o certificato di residenza',
      'Copia di ente religioso attestante natura incarico',
      'Indicazione mezzi sostentamento (vitto e alloggio)',
      'Polizza assicurativa o iscrizione al SSN',
    ],
    infoExtra: '',
    possoConvertire: '',
  },
  {
    notionName: 'Residenza elettiva',
    treeKey: 'res_elettiva',
    category: 'Studio/Lavoro',
    duration: '1 anno',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 80.46 €',
      'Copia del passaporto (non scaduto)',
      'Dichiarazione di ospitalità o contratto di affitto o certificato di residenza',
      'Permesso in scadenza',
    ],
    infoExtra: '',
    possoConvertire: 'Si, dopo 5 anni pds lungo periodo',
  },
  {
    notionName: 'Ricerca scientifica',
    treeKey: 'ricerca',
    category: 'Studio/Lavoro',
    duration: 'max 2 anni',
    rinnovoNonApplicabile: false,
    modRinnovo: [],
    docRinnovo: [
    ],
    infoExtra: '',
    possoConvertire: '',
  },
  {
    notionName: 'Richiesta Asilo',
    treeKey: 'rich_asilo',
    category: 'Protezione',
    duration: '6 mesi',
    rinnovoNonApplicabile: false,
    modRinnovo: ['personalmente'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Attestato nominativo',
      'Modello C3',
      'Se hai un ricorso in tribunale stampa del fascicolo telematico in Tribunale (chiedi al tuo avvocato)',
    ],
    infoExtra: 'Attenzione: alcune Questura potrebbero richiedere una dichiarazione di ospitalità, ma questo non è richiesto dalla legge!',
    possoConvertire: 'no',
  },
  {
    notionName: 'Sfruttamento lavorativo',
    treeKey: 'sfruttamento',
    category: 'Protezione',
    duration: '6 mesi',
    rinnovoNonApplicabile: false,
    modRinnovo: ['personalmente'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Copia del passaporto (non scaduto)',
      'Permesso in scadenza',
    ],
    infoExtra: 'ATTENZIONE: ALCUNE QUESTURE POTREBBERO RICHIEDERE IL PASSAPORTO\nNOTA: SCHEDA IN VIA DI VERIFICA\n',
    possoConvertire: 'si: studio, lavoro, attesa occupazione',
  },
  {
    notionName: 'Attività sportiva',
    treeKey: 'sportiva',
    category: 'Studio/Lavoro',
    duration: '',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 80.46 €',
      'Copia del passaporto (non scaduto)',
      'Dichiarazione di ospitalità o contratto di affitto o certificato di residenza',
      'Contratto con società sportiva',
      'Indicazione mezzi sostentamento (vitto e alloggio)',
    ],
    infoExtra: '',
    possoConvertire: 'SI: motivi di lavoro ',
  },
  {
    notionName: 'Lavoro subordinato stagionale (dopo ingresso con visto per "flussi stagionali")',
    treeKey: 'stagionale',
    category: 'Studio/Lavoro',
    duration: '2 anni',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 80.46 €',
      'Copia del passaporto (non scaduto)',
      'Dichiarazione di ospitalità o contratto di affitto o certificato di residenza',
      'Permesso in scadenza',
      'Contratto di lavoro',
      'Prova dei redditi (CUD e/o buste paga)',
      'Certificato UNILAV',
    ],
    infoExtra: '',
    possoConvertire: '',
  },
  {
    notionName: 'Studio (conversione da altro permesso)',
    treeKey: 'studio_conv',
    category: 'Studio/Lavoro',
    duration: '1 anno',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 70.46 €',
      'Copia del passaporto (non scaduto)',
      'Dichiarazione di ospitalità o contratto di affitto o certificato di residenza',
      'permesso precedente',
      'Documento di iscrizione ed esami sostenuti',
      'Garanzia economica (estratto conto bancario o borsa di studio o dichiarazione di familiari che ti mantengono)',
      'polizza assicurativa copertura sanitaria o iscrizione al Servizio Sanitario',
      'Polizza assicurativa copertura sanitaria o iscrizione volontaria a SSN',
    ],
    infoExtra: '',
    possoConvertire: 'si, mot di lavoro ',
  },
  {
    notionName: 'Studio (dopo ingresso con visto)',
    treeKey: 'studio_visto',
    category: 'Studio/Lavoro',
    duration: '1 anno',
    rinnovoNonApplicabile: false,
    modRinnovo: ['KIT'],
    docRinnovo: [
      'Marca da bollo da 16 €',
      '4 fototessere',
      'Bollettino postale da 70.46 o 80.46 (dipende dalla durata del permesso)',
      'Copia del passaporto (non scaduto)',
      'Dichiarazione di ospitalità o contratto di affitto o certificato di residenza',
      'Permesso in scadenza',
      'Certificato di iscrizione all\'anno accademico in corso',
      'Certificato esami sostenuti',
    ],
    infoExtra: '',
    possoConvertire: 'si, mot di lavoro ',
  },
  {
    notionName: 'Tirocinio',
    treeKey: 'tirocinio',
    category: 'Studio/Lavoro',
    duration: '1 anno',
    rinnovoNonApplicabile: false,
    modRinnovo: ['rinnovabile previa conversione'],
    docRinnovo: [
      'rinnovabile previa conversione',
    ],
    infoExtra: '',
    possoConvertire: '',
  },
];

/** Lookup by treeKey for quick access */
export const rinnovoByKey: Record<string, RinnovoPermit> = Object.fromEntries(
  rinnovoPermits.map(p => [p.treeKey, p]),
);
